markdown: rdiscount
excerpt_separator: ""
auto: true
pygments: true
title : Miracle Space
author :
  name : miracle åˆ˜
  email : liuhongyuan99@gmail.com
  github : miraclestar
production_url : http://blog.xmark.info
atom_path : /atom.xml
rss_path : /rss.xml